# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankimporter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawtransaction',
            old_name='Entry Date',
            new_name='entry_date',
        ),
        migrations.RenameField(
            model_name='rawtransaction',
            old_name='Payer/Payee',
            new_name='payer',
        ),
        migrations.RenameField(
            model_name='rawtransaction',
            old_name='Value Date',
            new_name='value_date',
        ),
    ]
