# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankimporter', '0003_auto_20170107_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtransaction',
            name='main_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_tag', to='bankimporter.Tag'),
        ),
    ]
